### ISSUE TITLE
Reset job failed flag

### ISSUE THREAD

**Issue by bibendi** [yabeda-rb/yabeda-schked#2]
Hi there!

We should reset a `job.opts[:failed]` flag here https://github.com/yabeda-rb/yabeda-schked/blob/197e5f1e552258b8eb10af2b92e4dd8f45d277b2/lib/yabeda/schked.rb#L41C17-L41C17

The reason is when an error was fired for the first time, we are constantly getting errors on our dashboard. It resets only after a pod restarting.
<img width="1667" alt="image" src="https://github.com/yabeda-rb/yabeda-schked/assets/320886/5948662b-9967-449d-b17e-c76f011de8f1">

**Comment by Envek** [comment]
Sorry, totally missed this issue! The fix has been released in [0.2.1](https://github.com/yabeda-rb/yabeda-schked/releases/tag/v0.2.1)

**Comment by bibendi** [comment]
Thank you!
